### ISSUE TITLE
Verovio neume line merge checklist

### ISSUE THREAD

**Issue by yinanazhou** [DDMAL/Neon2#1206]
Verovio:
- [x] insert staff
- [x] position of accid after staff rotation
- [x] split
- [x] unlink syllable: text is added, but doesn't draw the newly inserted bbox
- [x] group: group syllable doesn't work
- [x] ungroup: doesn't draw newly inserted bbox
- [x] staff reorder
- [x] insert syllable: doesn't draw newly inserted bbox
- [x] insert clef
- [x] update staff reorder based on new file structure
- [x] toggle ligature jumps in x-axis
- [x] update staff remove action #1211 
- [x] staff removing and sorting when there is only one staff in the file #1212

Neon:

- [x] out-of-bounds error when inserting elements in a created file #1210 

Docs:

- [x] Verovio-Neon file conversion
- [x] Verovio coordinate system conversion

Test:

- [x] Update test files

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, could you please test Neon using this [link](https://yinanazhou.github.io/Neon/) before I push the changes to "production" Neon?

**Comment by JoyfulGen** [comment]
@yinanazhou, just to be sure, am I just checking Neon's general functioning? In particular the things listed in your comment?

**Comment by JoyfulGen** [comment]
Ok! Update: I used Einsie 024r from the samples folder. I started playing with the staves, splitting the first one and adding a new staff to the top of the folio and then suddenly Neon became unresponsive and nothing I did worked. I refreshed the page and now no glyphs appear and the MEI status says "unknown"... I think I broke it. Sorryyy. Is the folio broken for you too?

UPDATE: I broke another one :) I was trying to find the sequence of events that triggered it and discovered the following:
- If I split a staff, then grouped it, then tried to change the tilt, all staves would become unresponsive.
- Once, I split the staff and then changed the tilt of one half and then suddenly all liquescents had a big X next to them. It was quite cool! I was trying to reproduce this when the MEI status became unknown again.

**Comment by yinanazhou** [comment]
> @yinanazhou, just to be sure, am I just checking Neon's general functioning? In particular the things listed in your comment?

@JoyfulGen Neon's general functioning. The checklist above are just the issues I found when I briefly test Neon. Thanks!

**Comment by yinanazhou** [comment]
> Ok! Update: I used Einsie 024r from the samples folder. I started playing with the staves, splitting the first one and adding a new staff to the top of the folio and then suddenly Neon became unresponsive and nothing I did worked. I refreshed the page and now no glyphs appear and the MEI status says "unknown"... I think I broke it. Sorryyy. Is the folio broken for you too?
> 
> UPDATE: I broke another one :) I was trying to find the sequence of events that triggered it and discovered the following:
> 
> * If I split a staff, then grouped it, then tried to change the tilt, all staves would become unresponsive.
> * Once, I split the staff and then changed the tilt of one half and then suddenly all liquescents had a big X next to them. It was quite cool! I was trying to reproduce this when the MEI status became unknown again.

@JoyfulGen, I've looked into this. Neon crashes because the `Remove` action in Verovio is not removing the entire `system-measure-staff` structure, instead it just removes the `staff`. I will let you know when I push the changes to staging. Thanks for pointing it out!

**Comment by JoyfulGen** [comment]
Hello again! I've found another odd behaviour. In Einsie folio 028r, I moved the last staff down to be able to create a new one in its place (I didn't want to delete a staff and break Neon again). Everything worked fine, except for one pair of neumes that refuse to group. If I try to group these two neumes with the neume, neume component, or syllable selector, I get a "Grouping Failed" notification. I've tried looking at the MEI and I can't see what's wrong! I also can't figure out what I did differently for these two neumes in particular.

Additional info: before I gave the two neumes a syllable nugget, their bounding boxes were invisible.


This is the MEI file: [CH-E_611_028r_bad_neumes.mei.zip](https://github.com/DDMAL/Neon/files/15331223/CH-E_611_028r_bad_neumes.mei.zip)
The two neumes are called "hello1" and "hello2"

**Comment by yinanazhou** [comment]
> Hello again! I've found another odd behaviour. In Einsie folio 028r, I moved the last staff down to be able to create a new one in its place (I didn't want to delete a staff and break Neon again). Everything worked fine, except for one pair of neumes that refuse to group. If I try to group these two neumes with the neume, neume component, or syllable selector, I get a "Grouping Failed" notification. I've tried looking at the MEI and I can't see what's wrong! I also can't figure out what I did differently for these two neumes in particular.
> 
> Additional info: before I gave the two neumes a syllable nugget, their bounding boxes were invisible.
> 
> This is the MEI file: [CH-E_611_028r_bad_neumes.mei.zip](https://github.com/DDMAL/Neon/files/15331223/CH-E_611_028r_bad_neumes.mei.zip) The two neumes are called "hello1" and "hello2"


Hi @JoyfulGen, about this bug, there is one space at the beginning of the file. I'm not sure if this is relevant to the bug, but I cannot reproduce it. I can group using both the `syllable` selector and the `neume` selector. Could you please check again?

But I did notice that if you selected a `divLine` and try to group using the `neume` selector, neon doesn't know that it should ignore the `divLine`. I will fix this.

Also, I noticed that the bounding boxes of the syllables after `hello1` and `hello2` are not showing. Is it the same for you? Do you remember what caused this?

**Comment by yinanazhou** [comment]
@JoyfulGen, I've pushed the changes for staff removing and sorting to Neon staging.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've checked all the items in this checklist. I will close this issue. If you find any new issues about neon staging with new Verovio, please create a new issue and mention you are using neon staging. Thanks!
