### ISSUE TITLE
Fix Ligature issues

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon2#190]
There seems to be a lot of small issues with ligatures so I decided to make a issue for all of them:

- [x] Dragging ligature issues (#187)
- [x] Refine Toggle Ligature options (#180)
- [x] Ligatures are seen as clivis' by infobox (#188)
- [x] Cannot group nc's into ligatures if there are in separate neumes/syllables. Warn users to group them into a neume first.
- [x] When dragging ligature will ungroup
- [x] Rendering of ligature is quite off at times (toggling/un-toggling).

**Comment by zoemcl** [comment]
The ungrouping of ligature upon drag occurs due to the reordering of neumes afterwards. This is a separate issue and therefore this one can be closed.
