### ISSUE TITLE
General UI issues

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon2#199]
There are several UI issues:

- [x] It is not responsive enough. It will look different on different screen and when resizing the window, portions of the controls will get cut off. (#183)
- [x] There is too much white space at the bottom of the screen. (more visible on certain screens).
- [x] Dropdown menus should be scrollable. PR #204
- [x] The sidebar menus should be scrollable independent to the editing canvas. 718c773
- [x] Non-stopping notification (#185) PR #208 
- [x] Make collapsed menu icons point to the right PR #204
- [x] Rename neume opacity to glyph opacity PR #204
- [x] Attempt to make the sliders the same size PR #204
- [x] Update cursor to another image when panning (Hand?) PR #204
- [x] Reformat hotkeys menu 
- [x] Rename Ncs to neume component in the grouping menu PR #204
- [x] A few people have mentioned not to use black as a highlighting colour. PR #204 
- [x] Give response to users upon group
- [x] Give response to users upon save PR #208

**Comment by zoemcl** [comment]
All have been implemented in various commits.
